default:
  image: node:lts-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

audit:
  stage: test
  script:
  - npm audit
  allow_failure: true

lint:
  stage: test
  script:
  - npm run lint
