default:
  image: node:22-alpine
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline --no-fund --no-audit

audit:
  stage: test
  script:
    - npm audit --omit dev
  allow_failure: true

lint:
  stage: test
  script:
    - npm run lint
