version: "3"
services:
  crypto-bot-father:
    image: danger89/crypto-bot-father:latest
    container_name: crypto-bot-father
    restart: always
    volumes:
      - /home/username/folder/to/.env:/app/.env:ro
    ports:
      - "127.0.0.1:3007:3007"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  crypto_bot_father_external_network:
